### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by miran97-bit** [schirrel/atom-ionic-run#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: macOS 12.1
**Thrown From**: [ionic](https://github.com/CoderSquirrel/atom-ionic-run) package 1.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/miran/.atom/packages/ionic/lib/ionic.js:80

TypeError: Cannot read property 'path' of undefined
    at Object.runCommand (/packages/ionic/lib/ionic.js:80:54)
    at HTMLElement.ionicBuildios (/packages/ionic/lib/ionic.js:33:33)
    at CommandRegistry.handleCommandEvent (/Users/miran/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:352326)
    at CommandRegistry.dispatch (/Users/miran/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:11:350801)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Users/miran/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:1:786918)
    at EventEmitter.t (/Users/miran/Desktop/Atom.app/Contents/Resources/app/static/<embedded>:1:794889)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
     -0:03.4.0 ionic:buildios (div.tool-panel.tree-view)
```

### Non-Core Packages

```
ionic 1.3.0 
```

**Comment by schirrel** [comment]
Hi @miran97-bit thanks for reporting the issue, i've found how to fix it and open a pr, but i having a couple of trouble with atom publication because i've change my username a few years ago. I already got in touch with the atom team, i will get back to u soon, sorry for that

**Comment by schirrel** [comment]
@miran97-bit got it work now 🙏 
just update your version on https://atom.io/packages/ionic
